version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
    - GITHUB_APP_CLIENT_ID=${GITHUB_APP_CLIENT_ID}
    - GITHUB_APP_CLIENT_SECRET=${GITHUB_APP_CLIENT_SECRET}
    - GITHUB_APP_ID=${GITHUB_APP_ID}
    - GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY}
    - SECRET_KEY=${SECRET_KEY}
    - BACKEND_HOST=${BACKEND_HOST}
    - FRONTEND_HOST=${FRONTEND_HOST}
    command: poetry run fastapi run sixdegrees/server.py
  frontend:
    build: ./REACT/six_degrees_of_connection
    ports:
      - "3000:3000"
    volumes:
      - ./REACT/six_degrees_of_connection:/app
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - FRONTEND_HOST=${FRONTEND_HOST}

    command: npm start
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend