version: '3.8'

services:
  backend:
    image: tobiadefami/six-degrees-of-torvalds-backend:v1.02
    build: ./sixdegrees
    ports:
      - "8000:8000"
    volumes:
      - ./sixdegrees:/app/sixdegrees
    environment:
    - GITHUB_APP_CLIENT_ID=${GITHUB_APP_CLIENT_ID}
    - GITHUB_APP_CLIENT_SECRET=${GITHUB_APP_CLIENT_SECRET}
    - GITHUB_APP_ID=${GITHUB_APP_ID}
    - SECRET_KEY=${SECRET_KEY}
    - BACKEND_HOST=${BACKEND_HOST}
    - FRONTEND_HOST=${FRONTEND_HOST}
    command: poetry run fastapi run sixdegrees/server.py
  frontend:
    image: tobiadefami/six-degrees-of-torvalds-frontend
    build: ./REACT/sixdegrees
    ports:
      - "3000:3000"
    volumes:
      - ./REACT/sixdegrees:/app
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - FRONTEND_HOST=${FRONTEND_HOST}
    command: npm start
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend